### ISSUE TITLE
看上去只建立了连接，但是命令不可以执行

### ISSUE THREAD

**Issue by CaiH123** [hero-tiger/far_control#1]
您好作者大大，这个项目看上去只建立了连接，但是命令不可以执行
![image](https://user-images.githubusercontent.com/64142048/228531520-f4f65d0c-36e1-48a8-8f3a-f40e56a1c267.png)
![image](https://user-images.githubusercontent.com/64142048/228531575-f9d76ba9-ba8b-4aeb-976b-891353749aee.png)

**Comment by hero-tiger** [comment]
养乐多
***@***.***


你好，oprate操作存在三种操作：shell&nbsp; upload download 三种模式&nbsp; 然后分别输入进入不同模式，输入exit退出当前模式。



                       
Original Email
                       
                     

Sender:"菜鸡CaiH"< ***@***.*** &gt;;

Sent Time:2023/3/29 20:12

To:"hero-tiger/far_control"< ***@***.*** &gt;;

Cc recipient:"Subscribed"< ***@***.*** &gt;;

Subject:[hero-tiger/far_control] 看上去只建立了连接，但是命令不可以执行 (Issue #1)




 
您好作者大大，这个项目看上去只建立了连接，但是命令不可以执行

**Comment by hero-tiger** [comment]
> 您好作者大大，这个项目看上去只建立了连接，但是命令不可以执行 ![image](https://user-images.githubusercontent.com/64142048/228531520-f4f65d0c-36e1-48a8-8f3a-f40e56a1c267.png) ![image](https://user-images.githubusercontent.com/64142048/228531575-f9d76ba9-ba8b-4aeb-976b-891353749aee.png)

你好，该项目三个主要功能，反弹shell 文件上传 文件下载 在oprate 分别输入 shell upload download 分别进入三种模式 exit 退出

**Comment by CaiH123** [comment]
已解决，谢谢作者大大
